### ISSUE TITLE
Nie znajdowanie tekstur wózków, pantografów itd

### ISSUE THREAD

**Issue by JGofficial** [Unofficial-MaSzyna-Developement/husarz_v4_lite#1]
![husarz błąd](https://user-images.githubusercontent.com/88037336/127368669-9d379ee0-2664-45ba-bd41-95a11907b51c.png)

**Comment by drozdzekk** [comment]
![image](https://user-images.githubusercontent.com/88037557/127382430-cb1cba62-c01f-494f-be19-81bae3ea69fa.png)

**Comment by Hirek193** [comment]
24h na dołączenie errors.txt

**Comment by drozdzekk** [comment]
> 24h na dołączenie error.txt

[errors.txt](https://github.com/Unofficial-MaSzyna-Developement/husarz_v4_lite/files/6896097/errors.txt)

**Comment by Hirek193** [comment]
Błąd spowodowany błędnym wgraniem dodatku. Nie wszystkie pliki ci się wrzuciły. Wgraj wszystko jeszcze raz na czysto.
![image](https://user-images.githubusercontent.com/23196899/127387970-5a006151-669c-41eb-918f-1003a468a0ef.png)
![image](https://user-images.githubusercontent.com/23196899/127388025-aebf946e-e688-42eb-ba64-ec5476bd6a13.png)

Zamykam
