### ISSUE TITLE
Problem z husarzem

### ISSUE THREAD

**Issue by adix091431** [Unofficial-MaSzyna-Developement/husarz_v4_lite#2]
Cześć hirek to ja Adix_#4616. Mam problem z kabiną husaza 
![Zrzut ekranu (1278)](https://user-images.githubusercontent.com/88160911/127545987-2d6dcc81-5581-4f1d-895e-68f34198515c.png)
![Zrzut ekranu (1277)](https://user-images.githubusercontent.com/88160911/127545995-b55db9f6-9afe-46cb-ad2a-b7fffce0bc42.png)

**Comment by adix091431** [comment]
A i zrobilem z instrukcją i dalej nie mam kabiny

**Comment by DriverPl** [comment]
Po pierwsze źle wgrałeś, a po drugie w paczce nie ma kabiny
